apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain # Default is Retain
parameters:
  type: io1
  iopsPerGB: "200" # (Min: 100 IOPS, Max: 64000 IOPS)
  fsType: ext4
