apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-expandable
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete # Default is Retain
allowVolumeExpansion: true # Added the ability to expand volume
parameters:
  type: gp2
  fsType: ext4
