repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: metrics-server
    namespace: kube-system
    chart: stable/metrics-server
    values:
      - args:
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
