apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::029718257588:role/eksctl-dev-cluster-1-nodegroup-de-NodeInstanceRole-1H91Y7LD8YA94
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::029718257588:role/eksctl-dev-cluster-1-nodegroup-de-NodeInstanceRole-VQ93SSYDXCG2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::029718257588:role/eksctl-dev-cluster-1-nodegroup-de-NodeInstanceRole-1A6AOMWTEZVQW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::029718257588:role/eksctl-dev-cluster-1-nodegroup-de-NodeInstanceRole-TVPRETX1Z02K
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::029718257588:role/ctm-architect-role
      username: admin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: aws-auth
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
