# Ref https://github.com/stefanprodan/k8s-podinfo/blob/master/docs/4-statefulsets.md
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

