apiVersion: v1
kind: ServiceAccount
metadata:
  name: %TEAM%
  namespace: %TEAM%-%ENV%
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: %TEAM%-%ENV%-tiller-manager
  namespace: %TEAM%-%ENV%
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  - autoscaling
  - policy
  resources:
    - '*'
  verbs:
    - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: %TEAM%-%ENV%-tiller-manager-binding
  namespace: %TEAM%-%ENV%
subjects:
- kind: ServiceAccount
  name: %TEAM%
  namespace: %TEAM%-%ENV%
roleRef:
  kind: Role
  name: %TEAM%
  apiGroup: rbac.authorization.k8s.io
