apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: build-cluster-1
  region: eu-west-1

nodeGroups:
  - name: build-cluster-1001-stateless
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
