apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster-3
  region: eu-west-1
  version: "1.18"

nodeGroups:
  - name: ng-bottlerocket-1006
    instanceType: m5.large
    desiredCapacity: 3
    maxSize: 5
    minSize: 3
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    amiFamily: Bottlerocket
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: snowsimple
        labels:
          env: dev
          checks: passed

vpc:
  cidr: 12.0.0.0/16
  #autoAllocateIPv6: true #This fails to delete
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (defaul

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager", "scheduler", "api"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

