apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guest-1234
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize-guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
