apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bogdan-curler-pvc
  labels:
    app: curler
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: curler


